import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."pr" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."pl" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."mr" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."ml" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."br" AS ENUM('none', 'default', 'accent');
  CREATE TYPE "public"."bl" AS ENUM('none', 'default', 'accent');
  CREATE TYPE "public"."bw" AS ENUM('thin', 'medium', 'thick');
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_border_width" "bw";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_padding_right" "pr";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_padding_left" "pl";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_margin_right" "mr";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_margin_left" "ml";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_border_right" "br";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_border_left" "bl";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_border_width" "bw";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_border_right";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_border_left";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_border_width";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_border_right";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_border_left";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_border_width";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_border_right";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_border_left";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_border_width";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_border_right";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_border_left";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_border_width";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_border_right";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_border_left";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_border_width";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_border_right";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_border_left";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_border_width";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_border_right";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_border_left";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_border_width";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_border_right";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_border_left";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_border_width";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_border_right";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_border_left";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_border_width";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_border_right";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_border_left";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_border_width";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_border_right";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_border_left";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_border_width";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_border_right";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_border_left";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_border_width";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_border_right";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_border_left";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_border_width";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_border_right";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_border_left";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_border_width";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_border_right";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_border_left";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_border_width";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_border_right";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_border_left";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_border_width";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_border_right";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_border_left";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_border_width";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_border_right";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_border_left";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_border_width";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_border_right";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_border_left";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_border_width";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_border_right";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_border_left";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_border_width";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_border_right";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_border_left";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_border_width";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_border_right";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_border_left";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_border_width";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_border_right";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_border_left";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_border_width";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_border_right";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_border_left";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_border_width";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_border_right";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_border_left";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_border_width";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_border_right";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_border_left";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_border_width";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_border_right";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_border_left";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_border_width";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_padding_right";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_padding_left";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_margin_right";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_margin_left";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_border_right";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_border_left";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_border_width";
  DROP TYPE "public"."pr";
  DROP TYPE "public"."pl";
  DROP TYPE "public"."mr";
  DROP TYPE "public"."ml";
  DROP TYPE "public"."br";
  DROP TYPE "public"."bl";
  DROP TYPE "public"."bw";`)
}
