import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."pt" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."pb" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."mt" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."mb" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."cw" AS ENUM('default', 'text', 'wide', 'full');
  CREATE TYPE "public"."bg" AS ENUM('default', 'raised', 'accent', 'dark');
  CREATE TYPE "public"."bt" AS ENUM('default', 'none', 'accent');
  CREATE TYPE "public"."bb" AS ENUM('none', 'default', 'accent');
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "cms_pages" ADD COLUMN "custom_c_s_s" varchar;
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_padding_top" "pt";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_padding_bottom" "pb";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_margin_top" "mt";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_margin_bottom" "mb";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_background" "bg";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_border_top" "bt";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_border_bottom" "bb";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_rounded" boolean;
  ALTER TABLE "_cms_pages_v" ADD COLUMN "version_custom_c_s_s" varchar;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_background";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_border_top";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_rounded";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_background";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_border_top";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_rounded";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_background";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_border_top";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_rounded";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_background";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_border_top";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_rounded";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_background";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_border_top";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_rounded";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_background";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_border_top";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_rounded";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_background";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_border_top";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_rounded";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_background";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_border_top";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_rounded";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_background";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_border_top";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_rounded";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_background";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_border_top";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_rounded";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_background";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_border_top";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_rounded";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_background";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_border_top";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_rounded";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_background";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_border_top";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_rounded";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_background";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_border_top";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_rounded";
  ALTER TABLE "cms_pages" DROP COLUMN "custom_c_s_s";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_background";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_border_top";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_rounded";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_background";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_border_top";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_rounded";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_background";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_border_top";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_rounded";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_background";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_border_top";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_rounded";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_background";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_border_top";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_rounded";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_background";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_border_top";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_rounded";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_background";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_border_top";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_rounded";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_background";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_border_top";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_rounded";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_background";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_border_top";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_rounded";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_background";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_border_top";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_rounded";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_background";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_border_top";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_rounded";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_background";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_border_top";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_rounded";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_background";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_border_top";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_rounded";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_padding_top";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_padding_bottom";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_margin_top";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_margin_bottom";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_background";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_border_top";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_border_bottom";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_rounded";
  ALTER TABLE "_cms_pages_v" DROP COLUMN "version_custom_c_s_s";
  DROP TYPE "public"."pt";
  DROP TYPE "public"."pb";
  DROP TYPE "public"."mt";
  DROP TYPE "public"."mb";
  DROP TYPE "public"."cw";
  DROP TYPE "public"."bg";
  DROP TYPE "public"."bt";
  DROP TYPE "public"."bb";`)
}
