import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  DROP INDEX IF EXISTS "cms_search_search_text_idx";
   CREATE TYPE "public"."mc" AS ENUM('1', '2');
  CREATE TYPE "public"."iw" AS ENUM('reading', 'standard', 'wide', 'full');
  CREATE TYPE "public"."cp" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."hs" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."enum_cms_pages_blocks_feature_grid_card_treatment" AS ENUM('separated', 'joined');
  CREATE TYPE "public"."enum_cms_pages_blocks_call_to_action_variant" AS ENUM('bordered', 'band');
  CREATE TYPE "public"."enum_cms_pages_blocks_call_to_action_button_surface" AS ENUM('default', 'light');
  CREATE TYPE "public"."enum_cms_pages_blocks_faq_variant" AS ENUM('disclosure', 'rows');
  CREATE TYPE "public"."enum_cms_pages_header_variant" AS ENUM('inherit', 'standard', 'minimal');
  CREATE TYPE "public"."enum__cms_pages_v_blocks_feature_grid_card_treatment" AS ENUM('separated', 'joined');
  CREATE TYPE "public"."enum__cms_pages_v_blocks_call_to_action_variant" AS ENUM('bordered', 'band');
  CREATE TYPE "public"."enum__cms_pages_v_blocks_call_to_action_button_surface" AS ENUM('default', 'light');
  CREATE TYPE "public"."enum__cms_pages_v_blocks_faq_variant" AS ENUM('disclosure', 'rows');
  CREATE TYPE "public"."enum__cms_pages_v_version_header_variant" AS ENUM('inherit', 'standard', 'minimal');
  CREATE TYPE "public"."enum_cms_header_navigation_social_links_icon" AS ENUM('apple', 'bluesky', 'discord', 'facebook', 'github', 'google-play', 'instagram', 'linkedin', 'mastodon', 'medium', 'pinterest', 'reddit', 'slack', 'spotify', 'telegram', 'threads', 'tiktok', 'twitch', 'whatsapp', 'twitter', 'youtube', 'arrow-right', 'arrow-up-right', 'bell', 'book-open', 'calendar', 'camera', 'check', 'chevron-right', 'help', 'cloud', 'download', 'external-link', 'file-text', 'globe', 'heart', 'home', 'image', 'info', 'link', 'lock', 'log-in', 'mail', 'map-pin', 'menu', 'message', 'phone', 'play', 'podcast', 'radio', 'rss', 'search', 'send', 'settings', 'share', 'shopping-bag', 'shopping-cart', 'sparkles', 'star', 'user', 'users', 'zap');
  CREATE TYPE "public"."enum_cms_header_navigation_items_treatment" AS ENUM('default', 'accent');
  CREATE TYPE "public"."enum_cms_header_navigation_variant" AS ENUM('standard', 'minimal');
  CREATE TYPE "public"."enum_cms_header_navigation_help_link_treatment" AS ENUM('default', 'accent');
  CREATE TYPE "public"."enum_cms_header_navigation_help_link_type" AS ENUM('page', 'post', 'url');
  CREATE TYPE "public"."enum_cms_header_navigation_help_link_icon" AS ENUM('apple', 'bluesky', 'discord', 'facebook', 'github', 'google-play', 'instagram', 'linkedin', 'mastodon', 'medium', 'pinterest', 'reddit', 'slack', 'spotify', 'telegram', 'threads', 'tiktok', 'twitch', 'whatsapp', 'twitter', 'youtube', 'arrow-right', 'arrow-up-right', 'bell', 'book-open', 'calendar', 'camera', 'check', 'chevron-right', 'help', 'cloud', 'download', 'external-link', 'file-text', 'globe', 'heart', 'home', 'image', 'info', 'link', 'lock', 'log-in', 'mail', 'map-pin', 'menu', 'message', 'phone', 'play', 'podcast', 'radio', 'rss', 'search', 'send', 'settings', 'share', 'shopping-bag', 'shopping-cart', 'sparkles', 'star', 'user', 'users', 'zap');
  CREATE TYPE "public"."enum_cms_footer_navigation_items_treatment" AS ENUM('default', 'accent');
  CREATE TYPE "public"."enum_cms_footer_navigation_layout_preset" AS ENUM('default', 'brand-details', 'stacked');
  CREATE TYPE "public"."enum_cms_footer_navigation_details_alignment" AS ENUM('start', 'end');
  CREATE TYPE "public"."enum_cms_footer_navigation_social_placement" AS ENUM('brand', 'details');
  CREATE TYPE "public"."enum_cms_site_settings_theme_heading_font" AS ENUM('system', 'poppins', 'inter', 'ibm-plex-mono');
  CREATE TYPE "public"."enum_cms_site_settings_theme_body_font" AS ENUM('system', 'poppins', 'inter', 'ibm-plex-mono');
  CREATE TYPE "public"."enum_cms_site_settings_theme_label_font" AS ENUM('system', 'poppins', 'inter', 'ibm-plex-mono');
  CREATE TYPE "public"."enum_cms_site_settings_theme_heading_weight" AS ENUM('600', '700', '800');
  CREATE TYPE "public"."enum_cms_site_settings_theme_typography_preset" AS ENUM('compact', 'standard', 'editorial');
  ALTER TYPE "public"."enum_cms_pages_blocks_feature_grid_layout" ADD VALUE 'process';
  ALTER TYPE "public"."enum__cms_pages_v_blocks_feature_grid_layout" ADD VALUE 'process';
  ALTER TYPE "public"."enum_cms_site_settings_theme_font_preset" ADD VALUE 'inter';
  ALTER TYPE "public"."enum_cms_site_settings_theme_font_preset" ADD VALUE 'ibm-plex-mono';
  CREATE TABLE "cms_header_navigation_social_links" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"label" varchar NOT NULL,
  	"url" varchar NOT NULL,
  	"icon" "enum_cms_header_navigation_social_links_icon" NOT NULL,
  	"new_tab" boolean
  );
  
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "cms_pages_blocks_feature_grid_items" ADD COLUMN "metadata" varchar;
  ALTER TABLE "cms_pages_blocks_feature_grid_items" ADD COLUMN "body" jsonb;
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "card_treatment" "enum_cms_pages_blocks_feature_grid_card_treatment";
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "cms_pages_blocks_portfolio_grid_items" ADD COLUMN "metadata" varchar;
  ALTER TABLE "cms_pages_blocks_portfolio_grid_items" ADD COLUMN "body" jsonb;
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "variant" "enum_cms_pages_blocks_call_to_action_variant";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "button_surface" "enum_cms_pages_blocks_call_to_action_button_surface";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "variant" "enum_cms_pages_blocks_faq_variant";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "cms_pages" ADD COLUMN "header_variant" "enum_cms_pages_header_variant";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid_items" ADD COLUMN "metadata" varchar;
  ALTER TABLE "_cms_pages_v_blocks_feature_grid_items" ADD COLUMN "body" jsonb;
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "card_treatment" "enum__cms_pages_v_blocks_feature_grid_card_treatment";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid_items" ADD COLUMN "metadata" varchar;
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid_items" ADD COLUMN "body" jsonb;
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "variant" "enum__cms_pages_v_blocks_call_to_action_variant";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "button_surface" "enum__cms_pages_v_blocks_call_to_action_button_surface";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "variant" "enum__cms_pages_v_blocks_faq_variant";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_mobile_columns" "mc";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_card_padding" "cp";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_heading_spacing" "hs";
  ALTER TABLE "_cms_pages_v" ADD COLUMN "version_header_variant" "enum__cms_pages_v_version_header_variant";
  ALTER TABLE "cms_header_navigation_items" ADD COLUMN "treatment" "enum_cms_header_navigation_items_treatment";
  ALTER TABLE "cms_header_navigation" ADD COLUMN "variant" "enum_cms_header_navigation_variant";
  ALTER TABLE "cms_header_navigation" ADD COLUMN "help_link_treatment" "enum_cms_header_navigation_help_link_treatment";
  ALTER TABLE "cms_header_navigation" ADD COLUMN "help_link_label" varchar;
  ALTER TABLE "cms_header_navigation" ADD COLUMN "help_link_type" "enum_cms_header_navigation_help_link_type";
  ALTER TABLE "cms_header_navigation" ADD COLUMN "help_link_icon" "enum_cms_header_navigation_help_link_icon";
  ALTER TABLE "cms_header_navigation" ADD COLUMN "help_link_page_id" integer;
  ALTER TABLE "cms_header_navigation" ADD COLUMN "help_link_post_id" integer;
  ALTER TABLE "cms_header_navigation" ADD COLUMN "help_link_url" varchar;
  ALTER TABLE "cms_header_navigation" ADD COLUMN "help_link_new_tab" boolean;
  ALTER TABLE "cms_header_navigation" ADD COLUMN "help_link_icon_only" boolean;
  ALTER TABLE "cms_footer_navigation_items" ADD COLUMN "treatment" "enum_cms_footer_navigation_items_treatment";
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "layout_preset" "enum_cms_footer_navigation_layout_preset";
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "details_alignment" "enum_cms_footer_navigation_details_alignment";
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "social_placement" "enum_cms_footer_navigation_social_placement";
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "details" varchar;
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "newsletter_appearance_mobile_columns" "mc";
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "newsletter_appearance_inner_width" "iw";
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "newsletter_appearance_card_padding" "cp";
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "newsletter_appearance_heading_spacing" "hs";
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "contact_form_appearance_mobile_columns" "mc";
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "contact_form_appearance_inner_width" "iw";
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "contact_form_appearance_card_padding" "cp";
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "contact_form_appearance_heading_spacing" "hs";
  ALTER TABLE "cms_site_settings" ADD COLUMN "theme_heading_font" "enum_cms_site_settings_theme_heading_font";
  ALTER TABLE "cms_site_settings" ADD COLUMN "theme_body_font" "enum_cms_site_settings_theme_body_font";
  ALTER TABLE "cms_site_settings" ADD COLUMN "theme_label_font" "enum_cms_site_settings_theme_label_font";
  ALTER TABLE "cms_site_settings" ADD COLUMN "theme_heading_weight" "enum_cms_site_settings_theme_heading_weight";
  ALTER TABLE "cms_site_settings" ADD COLUMN "theme_typography_preset" "enum_cms_site_settings_theme_typography_preset";
  ALTER TABLE "cms_site_settings" ADD COLUMN "theme_light_dark_surface" varchar DEFAULT '#0f0f0f' NOT NULL;
  ALTER TABLE "cms_site_settings" ADD COLUMN "theme_light_dark_ink" varchar DEFAULT '#ffffff' NOT NULL;
  ALTER TABLE "cms_site_settings" ADD COLUMN "theme_dark_dark_surface" varchar DEFAULT '#0f0f0f' NOT NULL;
  ALTER TABLE "cms_site_settings" ADD COLUMN "theme_dark_dark_ink" varchar DEFAULT '#ffffff' NOT NULL;
  ALTER TABLE "cms_header_navigation_social_links" ADD CONSTRAINT "cms_header_navigation_social_links_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."cms_header_navigation"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "cms_header_navigation_social_links_order_idx" ON "cms_header_navigation_social_links" USING btree ("_order");
  CREATE INDEX "cms_header_navigation_social_links_parent_id_idx" ON "cms_header_navigation_social_links" USING btree ("_parent_id");
  ALTER TABLE "cms_header_navigation" ADD CONSTRAINT "cms_header_navigation_help_link_page_id_cms_pages_id_fk" FOREIGN KEY ("help_link_page_id") REFERENCES "public"."cms_pages"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "cms_header_navigation" ADD CONSTRAINT "cms_header_navigation_help_link_post_id_cms_posts_id_fk" FOREIGN KEY ("help_link_post_id") REFERENCES "public"."cms_posts"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "cms_header_navigation_help_link_help_link_page_idx" ON "cms_header_navigation" USING btree ("help_link_page_id");
  CREATE INDEX "cms_header_navigation_help_link_help_link_post_idx" ON "cms_header_navigation" USING btree ("help_link_post_id");
`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  CREATE INDEX "cms_search_search_text_idx" ON "cms_search" USING btree ("search_text");
   ALTER TABLE "cms_header_navigation_social_links" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "cms_header_navigation_social_links" CASCADE;
  ALTER TABLE "cms_header_navigation" DROP CONSTRAINT "cms_header_navigation_help_link_page_id_cms_pages_id_fk";
  
  ALTER TABLE "cms_header_navigation" DROP CONSTRAINT "cms_header_navigation_help_link_post_id_cms_posts_id_fk";
  
  ALTER TABLE "cms_pages_blocks_feature_grid" ALTER COLUMN "layout" SET DATA TYPE text;
  ALTER TABLE "cms_pages_blocks_feature_grid" ALTER COLUMN "layout" SET DEFAULT 'cards'::text;
  DROP TYPE "public"."enum_cms_pages_blocks_feature_grid_layout";
  CREATE TYPE "public"."enum_cms_pages_blocks_feature_grid_layout" AS ENUM('cards', 'stacked', 'plain');
  ALTER TABLE "cms_pages_blocks_feature_grid" ALTER COLUMN "layout" SET DEFAULT 'cards'::"public"."enum_cms_pages_blocks_feature_grid_layout";
  ALTER TABLE "cms_pages_blocks_feature_grid" ALTER COLUMN "layout" SET DATA TYPE "public"."enum_cms_pages_blocks_feature_grid_layout" USING "layout"::"public"."enum_cms_pages_blocks_feature_grid_layout";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ALTER COLUMN "layout" SET DATA TYPE text;
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ALTER COLUMN "layout" SET DEFAULT 'cards'::text;
  DROP TYPE "public"."enum__cms_pages_v_blocks_feature_grid_layout";
  CREATE TYPE "public"."enum__cms_pages_v_blocks_feature_grid_layout" AS ENUM('cards', 'stacked', 'plain');
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ALTER COLUMN "layout" SET DEFAULT 'cards'::"public"."enum__cms_pages_v_blocks_feature_grid_layout";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ALTER COLUMN "layout" SET DATA TYPE "public"."enum__cms_pages_v_blocks_feature_grid_layout" USING "layout"::"public"."enum__cms_pages_v_blocks_feature_grid_layout";
  ALTER TABLE "cms_site_settings" ALTER COLUMN "theme_font_preset" SET DATA TYPE text;
  ALTER TABLE "cms_site_settings" ALTER COLUMN "theme_font_preset" SET DEFAULT 'poppins'::text;
  DROP TYPE "public"."enum_cms_site_settings_theme_font_preset";
  CREATE TYPE "public"."enum_cms_site_settings_theme_font_preset" AS ENUM('poppins', 'system');
  ALTER TABLE "cms_site_settings" ALTER COLUMN "theme_font_preset" SET DEFAULT 'poppins'::"public"."enum_cms_site_settings_theme_font_preset";
  ALTER TABLE "cms_site_settings" ALTER COLUMN "theme_font_preset" SET DATA TYPE "public"."enum_cms_site_settings_theme_font_preset" USING "theme_font_preset"::"public"."enum_cms_site_settings_theme_font_preset";
  DROP INDEX "cms_header_navigation_help_link_help_link_page_idx";
  DROP INDEX "cms_header_navigation_help_link_help_link_post_idx";

  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "cms_pages_blocks_feature_grid_items" DROP COLUMN "metadata";
  ALTER TABLE "cms_pages_blocks_feature_grid_items" DROP COLUMN "body";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "card_treatment";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "cms_pages_blocks_portfolio_grid_items" DROP COLUMN "metadata";
  ALTER TABLE "cms_pages_blocks_portfolio_grid_items" DROP COLUMN "body";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "variant";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "button_surface";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "variant";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "cms_pages" DROP COLUMN "header_variant";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid_items" DROP COLUMN "metadata";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid_items" DROP COLUMN "body";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "card_treatment";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid_items" DROP COLUMN "metadata";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid_items" DROP COLUMN "body";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "variant";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "button_surface";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "variant";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_mobile_columns";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_card_padding";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_heading_spacing";
  ALTER TABLE "_cms_pages_v" DROP COLUMN "version_header_variant";
  ALTER TABLE "cms_header_navigation_items" DROP COLUMN "treatment";
  ALTER TABLE "cms_header_navigation" DROP COLUMN "variant";
  ALTER TABLE "cms_header_navigation" DROP COLUMN "help_link_treatment";
  ALTER TABLE "cms_header_navigation" DROP COLUMN "help_link_label";
  ALTER TABLE "cms_header_navigation" DROP COLUMN "help_link_type";
  ALTER TABLE "cms_header_navigation" DROP COLUMN "help_link_icon";
  ALTER TABLE "cms_header_navigation" DROP COLUMN "help_link_page_id";
  ALTER TABLE "cms_header_navigation" DROP COLUMN "help_link_post_id";
  ALTER TABLE "cms_header_navigation" DROP COLUMN "help_link_url";
  ALTER TABLE "cms_header_navigation" DROP COLUMN "help_link_new_tab";
  ALTER TABLE "cms_header_navigation" DROP COLUMN "help_link_icon_only";
  ALTER TABLE "cms_footer_navigation_items" DROP COLUMN "treatment";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "layout_preset";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "details_alignment";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "social_placement";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "details";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "newsletter_appearance_mobile_columns";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "newsletter_appearance_inner_width";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "newsletter_appearance_card_padding";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "newsletter_appearance_heading_spacing";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "contact_form_appearance_mobile_columns";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "contact_form_appearance_inner_width";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "contact_form_appearance_card_padding";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "contact_form_appearance_heading_spacing";
  ALTER TABLE "cms_site_settings" DROP COLUMN "theme_heading_font";
  ALTER TABLE "cms_site_settings" DROP COLUMN "theme_body_font";
  ALTER TABLE "cms_site_settings" DROP COLUMN "theme_label_font";
  ALTER TABLE "cms_site_settings" DROP COLUMN "theme_heading_weight";
  ALTER TABLE "cms_site_settings" DROP COLUMN "theme_typography_preset";
  ALTER TABLE "cms_site_settings" DROP COLUMN "theme_light_dark_surface";
  ALTER TABLE "cms_site_settings" DROP COLUMN "theme_light_dark_ink";
  ALTER TABLE "cms_site_settings" DROP COLUMN "theme_dark_dark_surface";
  ALTER TABLE "cms_site_settings" DROP COLUMN "theme_dark_dark_ink";
  DROP TYPE "public"."mc";
  DROP TYPE "public"."iw";
  DROP TYPE "public"."cp";
  DROP TYPE "public"."hs";
  DROP TYPE "public"."enum_cms_pages_blocks_feature_grid_card_treatment";
  DROP TYPE "public"."enum_cms_pages_blocks_call_to_action_variant";
  DROP TYPE "public"."enum_cms_pages_blocks_call_to_action_button_surface";
  DROP TYPE "public"."enum_cms_pages_blocks_faq_variant";
  DROP TYPE "public"."enum_cms_pages_header_variant";
  DROP TYPE "public"."enum__cms_pages_v_blocks_feature_grid_card_treatment";
  DROP TYPE "public"."enum__cms_pages_v_blocks_call_to_action_variant";
  DROP TYPE "public"."enum__cms_pages_v_blocks_call_to_action_button_surface";
  DROP TYPE "public"."enum__cms_pages_v_blocks_faq_variant";
  DROP TYPE "public"."enum__cms_pages_v_version_header_variant";
  DROP TYPE "public"."enum_cms_header_navigation_social_links_icon";
  DROP TYPE "public"."enum_cms_header_navigation_items_treatment";
  DROP TYPE "public"."enum_cms_header_navigation_variant";
  DROP TYPE "public"."enum_cms_header_navigation_help_link_treatment";
  DROP TYPE "public"."enum_cms_header_navigation_help_link_type";
  DROP TYPE "public"."enum_cms_header_navigation_help_link_icon";
  DROP TYPE "public"."enum_cms_footer_navigation_items_treatment";
  DROP TYPE "public"."enum_cms_footer_navigation_layout_preset";
  DROP TYPE "public"."enum_cms_footer_navigation_details_alignment";
  DROP TYPE "public"."enum_cms_footer_navigation_social_placement";
  DROP TYPE "public"."enum_cms_site_settings_theme_heading_font";
  DROP TYPE "public"."enum_cms_site_settings_theme_body_font";
  DROP TYPE "public"."enum_cms_site_settings_theme_label_font";
  DROP TYPE "public"."enum_cms_site_settings_theme_heading_weight";
  DROP TYPE "public"."enum_cms_site_settings_theme_typography_preset";`)
}
