import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_cms_pages_blocks_hero_variant" AS ENUM('split', 'text', 'background');
  CREATE TYPE "public"."enum_cms_pages_blocks_hero_alignment" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_cms_pages_blocks_hero_height" AS ENUM('compact', 'standard', 'tall');
  CREATE TYPE "public"."pub_heading_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."pub_action_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."pub_columns" AS ENUM('auto', '2', '3', '4');
  CREATE TYPE "public"."enum_cms_pages_blocks_contact_form_name_mode" AS ENUM('combined', 'separate');
  CREATE TYPE "public"."enum_cms_pages_blocks_latest_posts_source" AS ENUM('latest', 'category', 'selected');
  CREATE TYPE "public"."pub_image_proportion" AS ENUM('landscape', 'square', 'original');
  CREATE TYPE "public"."pub_post_presentation" AS ENUM('card', 'imageOnly', 'simple');
  CREATE TYPE "public"."enum_cms_pages_blocks_latest_posts_action_type" AS ENUM('page', 'post', 'url');
  CREATE TYPE "public"."enum_cms_pages_blocks_latest_posts_action_icon" AS ENUM('apple', 'bluesky', 'discord', 'facebook', 'github', 'google-play', 'instagram', 'linkedin', 'mastodon', 'medium', 'pinterest', 'reddit', 'slack', 'spotify', 'telegram', 'threads', 'tiktok', 'twitch', 'whatsapp', 'twitter', 'youtube', 'arrow-right', 'arrow-up-right', 'bell', 'book-open', 'calendar', 'camera', 'check', 'chevron-right', 'help', 'cloud', 'download', 'external-link', 'file-text', 'globe', 'heart', 'home', 'image', 'info', 'link', 'lock', 'log-in', 'mail', 'map-pin', 'menu', 'message', 'phone', 'play', 'podcast', 'radio', 'rss', 'search', 'send', 'settings', 'share', 'shopping-bag', 'shopping-cart', 'sparkles', 'star', 'user', 'users', 'zap');
  CREATE TYPE "public"."enum_cms_pages_blocks_latest_posts_action_icon_position" AS ENUM('left', 'right');
  CREATE TYPE "public"."enum_cms_pages_blocks_latest_posts_action_variant" AS ENUM('primary-filled', 'primary-outline', 'secondary-filled', 'secondary-outline');
  CREATE TYPE "public"."enum__cms_pages_v_blocks_hero_variant" AS ENUM('split', 'text', 'background');
  CREATE TYPE "public"."enum__cms_pages_v_blocks_hero_alignment" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__cms_pages_v_blocks_hero_height" AS ENUM('compact', 'standard', 'tall');
  CREATE TYPE "public"."enum__cms_pages_v_blocks_contact_form_name_mode" AS ENUM('combined', 'separate');
  CREATE TYPE "public"."enum__cms_pages_v_blocks_latest_posts_source" AS ENUM('latest', 'category', 'selected');
  CREATE TYPE "public"."enum__cms_pages_v_blocks_latest_posts_action_type" AS ENUM('page', 'post', 'url');
  CREATE TYPE "public"."enum__cms_pages_v_blocks_latest_posts_action_icon" AS ENUM('apple', 'bluesky', 'discord', 'facebook', 'github', 'google-play', 'instagram', 'linkedin', 'mastodon', 'medium', 'pinterest', 'reddit', 'slack', 'spotify', 'telegram', 'threads', 'tiktok', 'twitch', 'whatsapp', 'twitter', 'youtube', 'arrow-right', 'arrow-up-right', 'bell', 'book-open', 'calendar', 'camera', 'check', 'chevron-right', 'help', 'cloud', 'download', 'external-link', 'file-text', 'globe', 'heart', 'home', 'image', 'info', 'link', 'lock', 'log-in', 'mail', 'map-pin', 'menu', 'message', 'phone', 'play', 'podcast', 'radio', 'rss', 'search', 'send', 'settings', 'share', 'shopping-bag', 'shopping-cart', 'sparkles', 'star', 'user', 'users', 'zap');
  CREATE TYPE "public"."enum__cms_pages_v_blocks_latest_posts_action_icon_position" AS ENUM('left', 'right');
  CREATE TYPE "public"."enum__cms_pages_v_blocks_latest_posts_action_variant" AS ENUM('primary-filled', 'primary-outline', 'secondary-filled', 'secondary-outline');
  CREATE TYPE "public"."enum_cms_footer_navigation_contact_form_name_mode" AS ENUM('combined', 'separate');
  CREATE TYPE "public"."pub_archive_presentation" AS ENUM('card', 'simple');
  CREATE TYPE "public"."pub_title_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."pub_title_surface" AS ENUM('default', 'raised', 'accent', 'dark', 'light');
  CREATE TYPE "public"."pub_list_surface" AS ENUM('default', 'raised', 'accent', 'dark', 'light');
  ALTER TYPE "public"."bg" ADD VALUE 'light';
  ALTER TYPE "public"."enum_cms_pages_blocks_feature_grid_layout" ADD VALUE 'plain';
  ALTER TYPE "public"."enum__cms_pages_v_blocks_feature_grid_layout" ADD VALUE 'plain';
  CREATE TABLE "cms_pages_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" integer NOT NULL,
  	"path" varchar NOT NULL,
  	"cms_posts_id" integer
  );
  
  CREATE TABLE "_cms_pages_v_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" integer NOT NULL,
  	"path" varchar NOT NULL,
  	"cms_posts_id" integer
  );
  
ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "variant" "enum_cms_pages_blocks_hero_variant";
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "alignment" "enum_cms_pages_blocks_hero_alignment";
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "height" "enum_cms_pages_blocks_hero_height";
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "focal_x" numeric DEFAULT 50;
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "focal_y" numeric DEFAULT 50;
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "overlay" numeric DEFAULT 50;
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "cms_pages_blocks_feature_grid_items" ADD COLUMN "rule_color" varchar;
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "numbered" boolean;
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "name_mode" "enum_cms_pages_blocks_contact_form_name_mode";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "show_company" boolean;
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "source" "enum_cms_pages_blocks_latest_posts_source";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "category_id" integer;
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "image_proportion" "pub_image_proportion";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "presentation" "pub_post_presentation";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "action_label" varchar;
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "action_type" "enum_cms_pages_blocks_latest_posts_action_type" DEFAULT 'page';
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "action_icon" "enum_cms_pages_blocks_latest_posts_action_icon";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "action_page_id" integer;
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "action_post_id" integer;
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "action_url" varchar;
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "action_new_tab" boolean DEFAULT false;
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "action_icon_position" "enum_cms_pages_blocks_latest_posts_action_icon_position" DEFAULT 'right';
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "action_variant" "enum_cms_pages_blocks_latest_posts_action_variant" DEFAULT 'primary-outline';
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "variant" "enum__cms_pages_v_blocks_hero_variant";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "alignment" "enum__cms_pages_v_blocks_hero_alignment";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "height" "enum__cms_pages_v_blocks_hero_height";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "focal_x" numeric DEFAULT 50;
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "focal_y" numeric DEFAULT 50;
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "overlay" numeric DEFAULT 50;
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid_items" ADD COLUMN "rule_color" varchar;
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "numbered" boolean;
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "name_mode" "enum__cms_pages_v_blocks_contact_form_name_mode";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "show_company" boolean;
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "source" "enum__cms_pages_v_blocks_latest_posts_source";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "category_id" integer;
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "image_proportion" "pub_image_proportion";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "presentation" "pub_post_presentation";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "action_label" varchar;
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "action_type" "enum__cms_pages_v_blocks_latest_posts_action_type" DEFAULT 'page';
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "action_icon" "enum__cms_pages_v_blocks_latest_posts_action_icon";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "action_page_id" integer;
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "action_post_id" integer;
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "action_url" varchar;
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "action_new_tab" boolean DEFAULT false;
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "action_icon_position" "enum__cms_pages_v_blocks_latest_posts_action_icon_position" DEFAULT 'right';
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "action_variant" "enum__cms_pages_v_blocks_latest_posts_action_variant" DEFAULT 'primary-outline';
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_action_alignment" "pub_action_align";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_columns" "pub_columns";
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "newsletter_appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "newsletter_appearance_action_alignment" "pub_action_align";
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "newsletter_appearance_columns" "pub_columns";
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "contact_form_name_mode" "enum_cms_footer_navigation_contact_form_name_mode";
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "contact_form_show_company" boolean;
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "contact_form_appearance_heading_alignment" "pub_heading_align";
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "contact_form_appearance_action_alignment" "pub_action_align";
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "contact_form_appearance_columns" "pub_columns";
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "latest_posts_limit" numeric DEFAULT 2;
  ALTER TABLE "cms_site_settings" ADD COLUMN "archive_page_size" numeric DEFAULT 12;
  ALTER TABLE "cms_site_settings" ADD COLUMN "archive_columns" "pub_columns";
  ALTER TABLE "cms_site_settings" ADD COLUMN "archive_image_proportion" "pub_image_proportion";
  ALTER TABLE "cms_site_settings" ADD COLUMN "archive_presentation" "pub_archive_presentation";
  ALTER TABLE "cms_site_settings" ADD COLUMN "archive_title_alignment" "pub_title_align";
  ALTER TABLE "cms_site_settings" ADD COLUMN "archive_title_surface" "pub_title_surface";
  ALTER TABLE "cms_site_settings" ADD COLUMN "archive_list_surface" "pub_list_surface";
  ALTER TABLE "cms_pages_rels" ADD CONSTRAINT "cms_pages_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."cms_pages"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms_pages_rels" ADD CONSTRAINT "cms_pages_rels_posts_fk" FOREIGN KEY ("cms_posts_id") REFERENCES "public"."cms_posts"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_cms_pages_v_rels" ADD CONSTRAINT "_cms_pages_v_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."_cms_pages_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_cms_pages_v_rels" ADD CONSTRAINT "_cms_pages_v_rels_posts_fk" FOREIGN KEY ("cms_posts_id") REFERENCES "public"."cms_posts"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "cms_pages_rels_order_idx" ON "cms_pages_rels" USING btree ("order");
  CREATE INDEX "cms_pages_rels_parent_idx" ON "cms_pages_rels" USING btree ("parent_id");
  CREATE INDEX "cms_pages_rels_path_idx" ON "cms_pages_rels" USING btree ("path");
  CREATE INDEX "cms_pages_rels_cms_posts_id_idx" ON "cms_pages_rels" USING btree ("cms_posts_id");
  CREATE INDEX "_cms_pages_v_rels_order_idx" ON "_cms_pages_v_rels" USING btree ("order");
  CREATE INDEX "_cms_pages_v_rels_parent_idx" ON "_cms_pages_v_rels" USING btree ("parent_id");
  CREATE INDEX "_cms_pages_v_rels_path_idx" ON "_cms_pages_v_rels" USING btree ("path");
  CREATE INDEX "_cms_pages_v_rels_cms_posts_id_idx" ON "_cms_pages_v_rels" USING btree ("cms_posts_id");
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD CONSTRAINT "cms_pages_blocks_latest_posts_category_id_cms_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."cms_categories"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD CONSTRAINT "cms_pages_blocks_latest_posts_action_page_id_cms_pages_id_fk" FOREIGN KEY ("action_page_id") REFERENCES "public"."cms_pages"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD CONSTRAINT "cms_pages_blocks_latest_posts_action_post_id_cms_posts_id_fk" FOREIGN KEY ("action_post_id") REFERENCES "public"."cms_posts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD CONSTRAINT "_cms_pages_v_blocks_latest_posts_category_id_cms_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."cms_categories"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD CONSTRAINT "_cms_pages_v_blocks_latest_posts_action_page_id_cms_pages_id_fk" FOREIGN KEY ("action_page_id") REFERENCES "public"."cms_pages"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD CONSTRAINT "_cms_pages_v_blocks_latest_posts_action_post_id_cms_posts_id_fk" FOREIGN KEY ("action_post_id") REFERENCES "public"."cms_posts"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "cms_pages_blocks_latest_posts_category_idx" ON "cms_pages_blocks_latest_posts" USING btree ("category_id");
  CREATE INDEX "cms_pages_blocks_latest_posts_action_action_page_idx" ON "cms_pages_blocks_latest_posts" USING btree ("action_page_id");
  CREATE INDEX "cms_pages_blocks_latest_posts_action_action_post_idx" ON "cms_pages_blocks_latest_posts" USING btree ("action_post_id");
  CREATE INDEX "_cms_pages_v_blocks_latest_posts_category_idx" ON "_cms_pages_v_blocks_latest_posts" USING btree ("category_id");
  CREATE INDEX "_cms_pages_v_blocks_latest_posts_action_action_page_idx" ON "_cms_pages_v_blocks_latest_posts" USING btree ("action_page_id");
  CREATE INDEX "_cms_pages_v_blocks_latest_posts_action_action_post_idx" ON "_cms_pages_v_blocks_latest_posts" USING btree ("action_post_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "cms_pages_rels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_cms_pages_v_rels" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "cms_pages_rels" CASCADE;
  DROP TABLE "_cms_pages_v_rels" CASCADE;
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP CONSTRAINT "cms_pages_blocks_latest_posts_category_id_cms_categories_id_fk";
  
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP CONSTRAINT "cms_pages_blocks_latest_posts_action_page_id_cms_pages_id_fk";
  
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP CONSTRAINT "cms_pages_blocks_latest_posts_action_post_id_cms_posts_id_fk";
  
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP CONSTRAINT "_cms_pages_v_blocks_latest_posts_category_id_cms_categories_id_fk";
  
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP CONSTRAINT "_cms_pages_v_blocks_latest_posts_action_page_id_cms_pages_id_fk";
  
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP CONSTRAINT "_cms_pages_v_blocks_latest_posts_action_post_id_cms_posts_id_fk";
  
  ALTER TABLE "cms_pages_blocks_hero" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "cms_pages_blocks_rich_text" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "cms_pages_blocks_image" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "cms_pages_blocks_feature_grid" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "cms_pages_blocks_split_content" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "cms_pages_blocks_link_grid" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "cms_pages_blocks_call_to_action" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "cms_pages_blocks_testimonials" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "cms_pages_blocks_logo_cloud" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "cms_pages_blocks_contact_form" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "cms_pages_blocks_stats" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "cms_pages_blocks_faq" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "cms_pages_blocks_latest_posts" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "_cms_pages_v_blocks_hero" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "_cms_pages_v_blocks_image" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "_cms_pages_v_blocks_split_content" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "_cms_pages_v_blocks_stats" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "_cms_pages_v_blocks_faq" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ALTER COLUMN "appearance_background" SET DATA TYPE text;
  ALTER TABLE "cms_footer_navigation" ALTER COLUMN "newsletter_appearance_background" SET DATA TYPE text;
  ALTER TABLE "cms_footer_navigation" ALTER COLUMN "contact_form_appearance_background" SET DATA TYPE text;
  DROP TYPE "public"."bg";
  CREATE TYPE "public"."bg" AS ENUM('default', 'raised', 'accent', 'dark');
  ALTER TABLE "cms_pages_blocks_hero" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "cms_pages_blocks_rich_text" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "cms_pages_blocks_image" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "cms_pages_blocks_feature_grid" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "cms_pages_blocks_split_content" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "cms_pages_blocks_link_grid" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "cms_pages_blocks_call_to_action" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "cms_pages_blocks_testimonials" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "cms_pages_blocks_contact_form" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "cms_pages_blocks_stats" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "cms_pages_blocks_faq" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "cms_pages_blocks_latest_posts" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "_cms_pages_v_blocks_hero" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "_cms_pages_v_blocks_image" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "_cms_pages_v_blocks_stats" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "_cms_pages_v_blocks_faq" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ALTER COLUMN "appearance_background" SET DATA TYPE "public"."bg" USING "appearance_background"::"public"."bg";
  ALTER TABLE "cms_footer_navigation" ALTER COLUMN "newsletter_appearance_background" SET DATA TYPE "public"."bg" USING "newsletter_appearance_background"::"public"."bg";
  ALTER TABLE "cms_footer_navigation" ALTER COLUMN "contact_form_appearance_background" SET DATA TYPE "public"."bg" USING "contact_form_appearance_background"::"public"."bg";
  ALTER TABLE "cms_pages_blocks_feature_grid" ALTER COLUMN "layout" SET DATA TYPE text;
  ALTER TABLE "cms_pages_blocks_feature_grid" ALTER COLUMN "layout" SET DEFAULT 'cards'::text;
  DROP TYPE "public"."enum_cms_pages_blocks_feature_grid_layout";
  CREATE TYPE "public"."enum_cms_pages_blocks_feature_grid_layout" AS ENUM('cards', 'stacked');
  ALTER TABLE "cms_pages_blocks_feature_grid" ALTER COLUMN "layout" SET DEFAULT 'cards'::"public"."enum_cms_pages_blocks_feature_grid_layout";
  ALTER TABLE "cms_pages_blocks_feature_grid" ALTER COLUMN "layout" SET DATA TYPE "public"."enum_cms_pages_blocks_feature_grid_layout" USING "layout"::"public"."enum_cms_pages_blocks_feature_grid_layout";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ALTER COLUMN "layout" SET DATA TYPE text;
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ALTER COLUMN "layout" SET DEFAULT 'cards'::text;
  DROP TYPE "public"."enum__cms_pages_v_blocks_feature_grid_layout";
  CREATE TYPE "public"."enum__cms_pages_v_blocks_feature_grid_layout" AS ENUM('cards', 'stacked');
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ALTER COLUMN "layout" SET DEFAULT 'cards'::"public"."enum__cms_pages_v_blocks_feature_grid_layout";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ALTER COLUMN "layout" SET DATA TYPE "public"."enum__cms_pages_v_blocks_feature_grid_layout" USING "layout"::"public"."enum__cms_pages_v_blocks_feature_grid_layout";
  DROP INDEX "cms_pages_blocks_latest_posts_category_idx";
  DROP INDEX "cms_pages_blocks_latest_posts_action_action_page_idx";
  DROP INDEX "cms_pages_blocks_latest_posts_action_action_post_idx";
  DROP INDEX "_cms_pages_v_blocks_latest_posts_category_idx";
  DROP INDEX "_cms_pages_v_blocks_latest_posts_action_action_page_idx";
  DROP INDEX "_cms_pages_v_blocks_latest_posts_action_action_post_idx";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "variant";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "alignment";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "height";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "focal_x";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "focal_y";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "overlay";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_columns";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_columns";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_columns";
  ALTER TABLE "cms_pages_blocks_feature_grid_items" DROP COLUMN "rule_color";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "numbered";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_columns";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_columns";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_columns";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_columns";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_columns";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_columns";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_columns";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "name_mode";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "show_company";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_columns";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_columns";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_columns";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "source";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "category_id";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "image_proportion";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "presentation";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "action_label";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "action_type";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "action_icon";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "action_page_id";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "action_post_id";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "action_url";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "action_new_tab";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "action_icon_position";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "action_variant";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_columns";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "variant";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "alignment";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "height";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "focal_x";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "focal_y";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "overlay";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_columns";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_columns";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_columns";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid_items" DROP COLUMN "rule_color";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "numbered";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_columns";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_columns";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_columns";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_columns";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_columns";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_columns";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_columns";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "name_mode";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "show_company";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_columns";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_columns";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_columns";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "source";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "category_id";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "image_proportion";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "presentation";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "action_label";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "action_type";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "action_icon";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "action_page_id";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "action_post_id";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "action_url";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "action_new_tab";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "action_icon_position";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "action_variant";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_heading_alignment";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_action_alignment";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_columns";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "newsletter_appearance_heading_alignment";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "newsletter_appearance_action_alignment";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "newsletter_appearance_columns";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "contact_form_name_mode";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "contact_form_show_company";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "contact_form_appearance_heading_alignment";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "contact_form_appearance_action_alignment";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "contact_form_appearance_columns";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "latest_posts_limit";
  ALTER TABLE "cms_site_settings" DROP COLUMN "archive_page_size";
  ALTER TABLE "cms_site_settings" DROP COLUMN "archive_columns";
  ALTER TABLE "cms_site_settings" DROP COLUMN "archive_image_proportion";
  ALTER TABLE "cms_site_settings" DROP COLUMN "archive_presentation";
  ALTER TABLE "cms_site_settings" DROP COLUMN "archive_title_alignment";
  ALTER TABLE "cms_site_settings" DROP COLUMN "archive_title_surface";
  ALTER TABLE "cms_site_settings" DROP COLUMN "archive_list_surface";
  DROP TYPE "public"."enum_cms_pages_blocks_hero_variant";
  DROP TYPE "public"."enum_cms_pages_blocks_hero_alignment";
  DROP TYPE "public"."enum_cms_pages_blocks_hero_height";
  DROP TYPE "public"."pub_heading_align";
  DROP TYPE "public"."pub_action_align";
  DROP TYPE "public"."pub_columns";
  DROP TYPE "public"."enum_cms_pages_blocks_contact_form_name_mode";
  DROP TYPE "public"."enum_cms_pages_blocks_latest_posts_source";
  DROP TYPE "public"."pub_image_proportion";
  DROP TYPE "public"."pub_post_presentation";
  DROP TYPE "public"."enum_cms_pages_blocks_latest_posts_action_type";
  DROP TYPE "public"."enum_cms_pages_blocks_latest_posts_action_icon";
  DROP TYPE "public"."enum_cms_pages_blocks_latest_posts_action_icon_position";
  DROP TYPE "public"."enum_cms_pages_blocks_latest_posts_action_variant";
  DROP TYPE "public"."enum__cms_pages_v_blocks_hero_variant";
  DROP TYPE "public"."enum__cms_pages_v_blocks_hero_alignment";
  DROP TYPE "public"."enum__cms_pages_v_blocks_hero_height";
  DROP TYPE "public"."enum__cms_pages_v_blocks_contact_form_name_mode";
  DROP TYPE "public"."enum__cms_pages_v_blocks_latest_posts_source";
  DROP TYPE "public"."enum__cms_pages_v_blocks_latest_posts_action_type";
  DROP TYPE "public"."enum__cms_pages_v_blocks_latest_posts_action_icon";
  DROP TYPE "public"."enum__cms_pages_v_blocks_latest_posts_action_icon_position";
  DROP TYPE "public"."enum__cms_pages_v_blocks_latest_posts_action_variant";
  DROP TYPE "public"."enum_cms_footer_navigation_contact_form_name_mode";
  DROP TYPE "public"."pub_archive_presentation";
  DROP TYPE "public"."pub_title_align";
  DROP TYPE "public"."pub_title_surface";
  DROP TYPE "public"."pub_list_surface";`)
}
