import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."pub_block_width" AS ENUM('page', 'full', 'padded');
  CREATE TYPE "public"."pub_page_width" AS ENUM('site', 'full', 'padded');
  CREATE TYPE "public"."pub_site_width" AS ENUM('full', 'padded');
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "cms_pages" ADD COLUMN "width" "pub_page_width" DEFAULT 'site';
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "_cms_pages_v" ADD COLUMN "version_width" "pub_page_width" DEFAULT 'site';
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "newsletter_appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "contact_form_appearance_width" "pub_block_width" DEFAULT 'page';
  ALTER TABLE "cms_site_settings" ADD COLUMN "width" "pub_site_width" DEFAULT 'padded';
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_content_width";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_inner_width";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_content_width";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "newsletter_appearance_inner_width";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "newsletter_appearance_content_width";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "contact_form_appearance_inner_width";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "contact_form_appearance_content_width";
  DROP TYPE "public"."iw";
  DROP TYPE "public"."cw";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  CREATE TYPE "public"."iw" AS ENUM('reading', 'standard', 'wide', 'full');
  CREATE TYPE "public"."cw" AS ENUM('default', 'text', 'wide', 'full');
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_hero" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_rich_text" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_image" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_feature_grid" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_split_content" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_link_grid" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_call_to_action" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_testimonials" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_logo_cloud" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_contact_form" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_stats" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_faq" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "cms_pages_blocks_latest_posts" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_hero" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_image" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_split_content" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_stats" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_faq" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_inner_width" "iw";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" ADD COLUMN "appearance_content_width" "cw";
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "newsletter_appearance_inner_width" "iw";
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "newsletter_appearance_content_width" "cw";
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "contact_form_appearance_inner_width" "iw";
  ALTER TABLE "cms_footer_navigation" ADD COLUMN "contact_form_appearance_content_width" "cw";
  ALTER TABLE "cms_pages_blocks_hero" DROP COLUMN "appearance_width";
  ALTER TABLE "cms_pages_blocks_rich_text" DROP COLUMN "appearance_width";
  ALTER TABLE "cms_pages_blocks_image" DROP COLUMN "appearance_width";
  ALTER TABLE "cms_pages_blocks_feature_grid" DROP COLUMN "appearance_width";
  ALTER TABLE "cms_pages_blocks_split_content" DROP COLUMN "appearance_width";
  ALTER TABLE "cms_pages_blocks_link_grid" DROP COLUMN "appearance_width";
  ALTER TABLE "cms_pages_blocks_portfolio_grid" DROP COLUMN "appearance_width";
  ALTER TABLE "cms_pages_blocks_call_to_action" DROP COLUMN "appearance_width";
  ALTER TABLE "cms_pages_blocks_testimonials" DROP COLUMN "appearance_width";
  ALTER TABLE "cms_pages_blocks_logo_cloud" DROP COLUMN "appearance_width";
  ALTER TABLE "cms_pages_blocks_contact_form" DROP COLUMN "appearance_width";
  ALTER TABLE "cms_pages_blocks_stats" DROP COLUMN "appearance_width";
  ALTER TABLE "cms_pages_blocks_faq" DROP COLUMN "appearance_width";
  ALTER TABLE "cms_pages_blocks_latest_posts" DROP COLUMN "appearance_width";
  ALTER TABLE "cms_pages" DROP COLUMN "width";
  ALTER TABLE "_cms_pages_v_blocks_hero" DROP COLUMN "appearance_width";
  ALTER TABLE "_cms_pages_v_blocks_rich_text" DROP COLUMN "appearance_width";
  ALTER TABLE "_cms_pages_v_blocks_image" DROP COLUMN "appearance_width";
  ALTER TABLE "_cms_pages_v_blocks_feature_grid" DROP COLUMN "appearance_width";
  ALTER TABLE "_cms_pages_v_blocks_split_content" DROP COLUMN "appearance_width";
  ALTER TABLE "_cms_pages_v_blocks_link_grid" DROP COLUMN "appearance_width";
  ALTER TABLE "_cms_pages_v_blocks_portfolio_grid" DROP COLUMN "appearance_width";
  ALTER TABLE "_cms_pages_v_blocks_call_to_action" DROP COLUMN "appearance_width";
  ALTER TABLE "_cms_pages_v_blocks_testimonials" DROP COLUMN "appearance_width";
  ALTER TABLE "_cms_pages_v_blocks_logo_cloud" DROP COLUMN "appearance_width";
  ALTER TABLE "_cms_pages_v_blocks_contact_form" DROP COLUMN "appearance_width";
  ALTER TABLE "_cms_pages_v_blocks_stats" DROP COLUMN "appearance_width";
  ALTER TABLE "_cms_pages_v_blocks_faq" DROP COLUMN "appearance_width";
  ALTER TABLE "_cms_pages_v_blocks_latest_posts" DROP COLUMN "appearance_width";
  ALTER TABLE "_cms_pages_v" DROP COLUMN "version_width";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "newsletter_appearance_width";
  ALTER TABLE "cms_footer_navigation" DROP COLUMN "contact_form_appearance_width";
  ALTER TABLE "cms_site_settings" DROP COLUMN "width";
  DROP TYPE "public"."pub_block_width";
  DROP TYPE "public"."pub_page_width";
  DROP TYPE "public"."pub_site_width";`)
}
