packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@supabase/auth-js@2.117.2'
  - '@supabase/functions-js@2.117.2'
  - '@supabase/postgrest-js@2.117.2'
  - '@supabase/realtime-js@2.117.2'
  - '@supabase/storage-js@2.117.2'
  - '@supabase/supabase-js@2.117.2'
  - '@tanstack/query-core@5.103.3'
  - '@tanstack/react-query@5.103.3'
  - react-native-web@0.21.3

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
