/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    authors: Author;
    categories: Category;
    tags: Tag;
    posts: Post;
    pages: Page;
    redirects: Redirect;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    headerNavigation: HeaderNavigation;
    footerNavigation: FooterNavigation;
    siteSettings: SiteSetting;
  };
  globalsSelect: {
    headerNavigation: HeaderNavigationSelect<false> | HeaderNavigationSelect<true>;
    footerNavigation: FooterNavigationSelect<false> | FooterNavigationSelect<true>;
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  slug: string;
  bio?: string | null;
  image?: (number | null) | Media;
  website?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  parent?: (number | null) | Category;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  summary: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: (number | null) | Author;
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  publishedAt?: string | null;
  /**
   * Show links to level-two and level-three headings in this article.
   */
  showTableOfContents?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout: (
    | {
        /**
         * Optional in-page anchor using lowercase letters, numbers, and hyphens.
         */
        anchor?: string | null;
        eyebrow?: string | null;
        /**
         * Select text and choose Accent from the toolbar. Use Shift+Enter for a line break.
         */
        heading: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        secondaryHeading?: string | null;
        body?: string | null;
        primaryButton?: {
          label?: string | null;
          url?: string | null;
        };
        secondaryButton?: {
          label?: string | null;
          url?: string | null;
        };
        image?: (number | null) | Media;
        /**
         * Optional layout and surface overrides. Defaults use the site design system.
         */
        appearance?: {
          contentWidth?: ('default' | 'text' | 'wide' | 'full') | null;
          background?: ('default' | 'raised' | 'accent' | 'dark') | null;
          rounded?: boolean | null;
          paddingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          borderTop?: ('default' | 'none' | 'accent') | null;
          borderRight?: ('none' | 'default' | 'accent') | null;
          borderBottom?: ('none' | 'default' | 'accent') | null;
          borderLeft?: ('none' | 'default' | 'accent') | null;
          borderWidth?: ('thin' | 'medium' | 'thick') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        /**
         * Optional in-page anchor using lowercase letters, numbers, and hyphens.
         */
        anchor?: string | null;
        /**
         * Optional short label displayed above the section heading or content.
         */
        eyebrow?: string | null;
        heading?: string | null;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Optional layout and surface overrides. Defaults use the site design system.
         */
        appearance?: {
          contentWidth?: ('default' | 'text' | 'wide' | 'full') | null;
          background?: ('default' | 'raised' | 'accent' | 'dark') | null;
          rounded?: boolean | null;
          paddingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          borderTop?: ('default' | 'none' | 'accent') | null;
          borderRight?: ('none' | 'default' | 'accent') | null;
          borderBottom?: ('none' | 'default' | 'accent') | null;
          borderLeft?: ('none' | 'default' | 'accent') | null;
          borderWidth?: ('thin' | 'medium' | 'thick') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        /**
         * Optional in-page anchor using lowercase letters, numbers, and hyphens.
         */
        anchor?: string | null;
        /**
         * Optional short label displayed above the section heading or content.
         */
        eyebrow?: string | null;
        image: number | Media;
        caption?: string | null;
        /**
         * Optional layout and surface overrides. Defaults use the site design system.
         */
        appearance?: {
          contentWidth?: ('default' | 'text' | 'wide' | 'full') | null;
          background?: ('default' | 'raised' | 'accent' | 'dark') | null;
          rounded?: boolean | null;
          paddingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          borderTop?: ('default' | 'none' | 'accent') | null;
          borderRight?: ('none' | 'default' | 'accent') | null;
          borderBottom?: ('none' | 'default' | 'accent') | null;
          borderLeft?: ('none' | 'default' | 'accent') | null;
          borderWidth?: ('thin' | 'medium' | 'thick') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'image';
      }
    | {
        /**
         * Optional in-page anchor using lowercase letters, numbers, and hyphens.
         */
        anchor?: string | null;
        eyebrow?: string | null;
        heading: string;
        intro?: string | null;
        layout?: ('cards' | 'stacked') | null;
        items?:
          | {
              title: string;
              description: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional single link shown after the section content.
         */
        action?: {
          label?: string | null;
          url?: string | null;
        };
        /**
         * Optional layout and surface overrides. Defaults use the site design system.
         */
        appearance?: {
          contentWidth?: ('default' | 'text' | 'wide' | 'full') | null;
          background?: ('default' | 'raised' | 'accent' | 'dark') | null;
          rounded?: boolean | null;
          paddingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          borderTop?: ('default' | 'none' | 'accent') | null;
          borderRight?: ('none' | 'default' | 'accent') | null;
          borderBottom?: ('none' | 'default' | 'accent') | null;
          borderLeft?: ('none' | 'default' | 'accent') | null;
          borderWidth?: ('thin' | 'medium' | 'thick') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'featureGrid';
      }
    | {
        /**
         * Optional in-page anchor using lowercase letters, numbers, and hyphens.
         */
        anchor?: string | null;
        eyebrow?: string | null;
        heading: string;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        image: number | Media;
        imagePosition: 'left' | 'right';
        /**
         * Optional single link shown after the section content.
         */
        action?: {
          label?: string | null;
          url?: string | null;
        };
        /**
         * Optional layout and surface overrides. Defaults use the site design system.
         */
        appearance?: {
          contentWidth?: ('default' | 'text' | 'wide' | 'full') | null;
          background?: ('default' | 'raised' | 'accent' | 'dark') | null;
          rounded?: boolean | null;
          paddingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          borderTop?: ('default' | 'none' | 'accent') | null;
          borderRight?: ('none' | 'default' | 'accent') | null;
          borderBottom?: ('none' | 'default' | 'accent') | null;
          borderLeft?: ('none' | 'default' | 'accent') | null;
          borderWidth?: ('thin' | 'medium' | 'thick') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'splitContent';
      }
    | {
        /**
         * Optional in-page anchor using lowercase letters, numbers, and hyphens.
         */
        anchor?: string | null;
        eyebrow?: string | null;
        heading: string;
        intro?: string | null;
        items?:
          | {
              label: string;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional single link shown after the section content.
         */
        action?: {
          label?: string | null;
          url?: string | null;
        };
        /**
         * Optional layout and surface overrides. Defaults use the site design system.
         */
        appearance?: {
          contentWidth?: ('default' | 'text' | 'wide' | 'full') | null;
          background?: ('default' | 'raised' | 'accent' | 'dark') | null;
          rounded?: boolean | null;
          paddingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          borderTop?: ('default' | 'none' | 'accent') | null;
          borderRight?: ('none' | 'default' | 'accent') | null;
          borderBottom?: ('none' | 'default' | 'accent') | null;
          borderLeft?: ('none' | 'default' | 'accent') | null;
          borderWidth?: ('thin' | 'medium' | 'thick') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'linkGrid';
      }
    | {
        /**
         * Optional in-page anchor using lowercase letters, numbers, and hyphens.
         */
        anchor?: string | null;
        eyebrow?: string | null;
        heading: string;
        intro?: string | null;
        items?:
          | {
              name: string;
              role?: string | null;
              description: string;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional single link shown after the section content.
         */
        action?: {
          label?: string | null;
          url?: string | null;
        };
        /**
         * Optional layout and surface overrides. Defaults use the site design system.
         */
        appearance?: {
          contentWidth?: ('default' | 'text' | 'wide' | 'full') | null;
          background?: ('default' | 'raised' | 'accent' | 'dark') | null;
          rounded?: boolean | null;
          paddingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          borderTop?: ('default' | 'none' | 'accent') | null;
          borderRight?: ('none' | 'default' | 'accent') | null;
          borderBottom?: ('none' | 'default' | 'accent') | null;
          borderLeft?: ('none' | 'default' | 'accent') | null;
          borderWidth?: ('thin' | 'medium' | 'thick') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'portfolioGrid';
      }
    | {
        /**
         * Optional in-page anchor using lowercase letters, numbers, and hyphens.
         */
        anchor?: string | null;
        /**
         * Optional short label displayed above the section heading or content.
         */
        eyebrow?: string | null;
        heading: string;
        body?: string | null;
        buttonLabel: string;
        buttonUrl: string;
        /**
         * Optional layout and surface overrides. Defaults use the site design system.
         */
        appearance?: {
          contentWidth?: ('default' | 'text' | 'wide' | 'full') | null;
          background?: ('default' | 'raised' | 'accent' | 'dark') | null;
          rounded?: boolean | null;
          paddingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          borderTop?: ('default' | 'none' | 'accent') | null;
          borderRight?: ('none' | 'default' | 'accent') | null;
          borderBottom?: ('none' | 'default' | 'accent') | null;
          borderLeft?: ('none' | 'default' | 'accent') | null;
          borderWidth?: ('thin' | 'medium' | 'thick') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'callToAction';
      }
    | {
        /**
         * Optional in-page anchor using lowercase letters, numbers, and hyphens.
         */
        anchor?: string | null;
        /**
         * Optional short label displayed above the section heading or content.
         */
        eyebrow?: string | null;
        heading?: string | null;
        items?:
          | {
              quote: string;
              name: string;
              role?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional layout and surface overrides. Defaults use the site design system.
         */
        appearance?: {
          contentWidth?: ('default' | 'text' | 'wide' | 'full') | null;
          background?: ('default' | 'raised' | 'accent' | 'dark') | null;
          rounded?: boolean | null;
          paddingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          borderTop?: ('default' | 'none' | 'accent') | null;
          borderRight?: ('none' | 'default' | 'accent') | null;
          borderBottom?: ('none' | 'default' | 'accent') | null;
          borderLeft?: ('none' | 'default' | 'accent') | null;
          borderWidth?: ('thin' | 'medium' | 'thick') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonials';
      }
    | {
        /**
         * Optional in-page anchor using lowercase letters, numbers, and hyphens.
         */
        anchor?: string | null;
        /**
         * Optional short label displayed above the section heading or content.
         */
        eyebrow?: string | null;
        heading?: string | null;
        intro?: string | null;
        items?:
          | {
              name: string;
              image: number | Media;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional layout and surface overrides. Defaults use the site design system.
         */
        appearance?: {
          contentWidth?: ('default' | 'text' | 'wide' | 'full') | null;
          background?: ('default' | 'raised' | 'accent' | 'dark') | null;
          rounded?: boolean | null;
          paddingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          borderTop?: ('default' | 'none' | 'accent') | null;
          borderRight?: ('none' | 'default' | 'accent') | null;
          borderBottom?: ('none' | 'default' | 'accent') | null;
          borderLeft?: ('none' | 'default' | 'accent') | null;
          borderWidth?: ('thin' | 'medium' | 'thick') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'logoCloud';
      }
    | {
        /**
         * Optional in-page anchor using lowercase letters, numbers, and hyphens.
         */
        anchor?: string | null;
        eyebrow?: string | null;
        heading: string;
        body?: string | null;
        submitLabel: string;
        successMessage: string;
        /**
         * Optional layout and surface overrides. Defaults use the site design system.
         */
        appearance?: {
          contentWidth?: ('default' | 'text' | 'wide' | 'full') | null;
          background?: ('default' | 'raised' | 'accent' | 'dark') | null;
          rounded?: boolean | null;
          paddingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          borderTop?: ('default' | 'none' | 'accent') | null;
          borderRight?: ('none' | 'default' | 'accent') | null;
          borderBottom?: ('none' | 'default' | 'accent') | null;
          borderLeft?: ('none' | 'default' | 'accent') | null;
          borderWidth?: ('thin' | 'medium' | 'thick') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'contactForm';
      }
    | {
        /**
         * Optional in-page anchor using lowercase letters, numbers, and hyphens.
         */
        anchor?: string | null;
        /**
         * Optional short label displayed above the section heading or content.
         */
        eyebrow?: string | null;
        heading?: string | null;
        items?:
          | {
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional layout and surface overrides. Defaults use the site design system.
         */
        appearance?: {
          contentWidth?: ('default' | 'text' | 'wide' | 'full') | null;
          background?: ('default' | 'raised' | 'accent' | 'dark') | null;
          rounded?: boolean | null;
          paddingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          borderTop?: ('default' | 'none' | 'accent') | null;
          borderRight?: ('none' | 'default' | 'accent') | null;
          borderBottom?: ('none' | 'default' | 'accent') | null;
          borderLeft?: ('none' | 'default' | 'accent') | null;
          borderWidth?: ('thin' | 'medium' | 'thick') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'stats';
      }
    | {
        /**
         * Optional in-page anchor using lowercase letters, numbers, and hyphens.
         */
        anchor?: string | null;
        /**
         * Optional short label displayed above the section heading or content.
         */
        eyebrow?: string | null;
        heading?: string | null;
        items?:
          | {
              question: string;
              answer: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional layout and surface overrides. Defaults use the site design system.
         */
        appearance?: {
          contentWidth?: ('default' | 'text' | 'wide' | 'full') | null;
          background?: ('default' | 'raised' | 'accent' | 'dark') | null;
          rounded?: boolean | null;
          paddingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          borderTop?: ('default' | 'none' | 'accent') | null;
          borderRight?: ('none' | 'default' | 'accent') | null;
          borderBottom?: ('none' | 'default' | 'accent') | null;
          borderLeft?: ('none' | 'default' | 'accent') | null;
          borderWidth?: ('thin' | 'medium' | 'thick') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        /**
         * Optional in-page anchor using lowercase letters, numbers, and hyphens.
         */
        anchor?: string | null;
        /**
         * Optional short label displayed above the section heading or content.
         */
        eyebrow?: string | null;
        heading?: string | null;
        limit?: number | null;
        /**
         * Optional layout and surface overrides. Defaults use the site design system.
         */
        appearance?: {
          contentWidth?: ('default' | 'text' | 'wide' | 'full') | null;
          background?: ('default' | 'raised' | 'accent' | 'dark') | null;
          rounded?: boolean | null;
          paddingTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          paddingLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginTop?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginRight?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginBottom?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          marginLeft?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
          borderTop?: ('default' | 'none' | 'accent') | null;
          borderRight?: ('none' | 'default' | 'accent') | null;
          borderBottom?: ('none' | 'default' | 'accent') | null;
          borderLeft?: ('none' | 'default' | 'accent') | null;
          borderWidth?: ('thin' | 'medium' | 'thick') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'latestPosts';
      }
  )[];
  /**
   * Optional escape hatch for trusted editors. Scope selectors to [data-page] to avoid affecting the admin or other pages.
   */
  customCSS?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  type: '301' | '302';
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'pages';
        value: number | Page;
      }
    | {
        relationTo: 'posts';
        value: number | Post;
      };
  excerpt?: string | null;
  searchText?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  image?: T;
  website?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  body?: T;
  author?: T;
  categories?: T;
  tags?: T;
  publishedAt?: T;
  showTableOfContents?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              secondaryHeading?: T;
              body?: T;
              primaryButton?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              secondaryButton?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              image?: T;
              appearance?:
                | T
                | {
                    contentWidth?: T;
                    background?: T;
                    rounded?: T;
                    paddingTop?: T;
                    paddingRight?: T;
                    paddingBottom?: T;
                    paddingLeft?: T;
                    marginTop?: T;
                    marginRight?: T;
                    marginBottom?: T;
                    marginLeft?: T;
                    borderTop?: T;
                    borderRight?: T;
                    borderBottom?: T;
                    borderLeft?: T;
                    borderWidth?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              content?: T;
              appearance?:
                | T
                | {
                    contentWidth?: T;
                    background?: T;
                    rounded?: T;
                    paddingTop?: T;
                    paddingRight?: T;
                    paddingBottom?: T;
                    paddingLeft?: T;
                    marginTop?: T;
                    marginRight?: T;
                    marginBottom?: T;
                    marginLeft?: T;
                    borderTop?: T;
                    borderRight?: T;
                    borderBottom?: T;
                    borderLeft?: T;
                    borderWidth?: T;
                  };
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              image?: T;
              caption?: T;
              appearance?:
                | T
                | {
                    contentWidth?: T;
                    background?: T;
                    rounded?: T;
                    paddingTop?: T;
                    paddingRight?: T;
                    paddingBottom?: T;
                    paddingLeft?: T;
                    marginTop?: T;
                    marginRight?: T;
                    marginBottom?: T;
                    marginLeft?: T;
                    borderTop?: T;
                    borderRight?: T;
                    borderBottom?: T;
                    borderLeft?: T;
                    borderWidth?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              intro?: T;
              layout?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              action?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              appearance?:
                | T
                | {
                    contentWidth?: T;
                    background?: T;
                    rounded?: T;
                    paddingTop?: T;
                    paddingRight?: T;
                    paddingBottom?: T;
                    paddingLeft?: T;
                    marginTop?: T;
                    marginRight?: T;
                    marginBottom?: T;
                    marginLeft?: T;
                    borderTop?: T;
                    borderRight?: T;
                    borderBottom?: T;
                    borderLeft?: T;
                    borderWidth?: T;
                  };
              id?: T;
              blockName?: T;
            };
        splitContent?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              content?: T;
              image?: T;
              imagePosition?: T;
              action?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              appearance?:
                | T
                | {
                    contentWidth?: T;
                    background?: T;
                    rounded?: T;
                    paddingTop?: T;
                    paddingRight?: T;
                    paddingBottom?: T;
                    paddingLeft?: T;
                    marginTop?: T;
                    marginRight?: T;
                    marginBottom?: T;
                    marginLeft?: T;
                    borderTop?: T;
                    borderRight?: T;
                    borderBottom?: T;
                    borderLeft?: T;
                    borderWidth?: T;
                  };
              id?: T;
              blockName?: T;
            };
        linkGrid?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              action?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              appearance?:
                | T
                | {
                    contentWidth?: T;
                    background?: T;
                    rounded?: T;
                    paddingTop?: T;
                    paddingRight?: T;
                    paddingBottom?: T;
                    paddingLeft?: T;
                    marginTop?: T;
                    marginRight?: T;
                    marginBottom?: T;
                    marginLeft?: T;
                    borderTop?: T;
                    borderRight?: T;
                    borderBottom?: T;
                    borderLeft?: T;
                    borderWidth?: T;
                  };
              id?: T;
              blockName?: T;
            };
        portfolioGrid?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    name?: T;
                    role?: T;
                    description?: T;
                    url?: T;
                    id?: T;
                  };
              action?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              appearance?:
                | T
                | {
                    contentWidth?: T;
                    background?: T;
                    rounded?: T;
                    paddingTop?: T;
                    paddingRight?: T;
                    paddingBottom?: T;
                    paddingLeft?: T;
                    marginTop?: T;
                    marginRight?: T;
                    marginBottom?: T;
                    marginLeft?: T;
                    borderTop?: T;
                    borderRight?: T;
                    borderBottom?: T;
                    borderLeft?: T;
                    borderWidth?: T;
                  };
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              body?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              appearance?:
                | T
                | {
                    contentWidth?: T;
                    background?: T;
                    rounded?: T;
                    paddingTop?: T;
                    paddingRight?: T;
                    paddingBottom?: T;
                    paddingLeft?: T;
                    marginTop?: T;
                    marginRight?: T;
                    marginBottom?: T;
                    marginLeft?: T;
                    borderTop?: T;
                    borderRight?: T;
                    borderBottom?: T;
                    borderLeft?: T;
                    borderWidth?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    quote?: T;
                    name?: T;
                    role?: T;
                    id?: T;
                  };
              appearance?:
                | T
                | {
                    contentWidth?: T;
                    background?: T;
                    rounded?: T;
                    paddingTop?: T;
                    paddingRight?: T;
                    paddingBottom?: T;
                    paddingLeft?: T;
                    marginTop?: T;
                    marginRight?: T;
                    marginBottom?: T;
                    marginLeft?: T;
                    borderTop?: T;
                    borderRight?: T;
                    borderBottom?: T;
                    borderLeft?: T;
                    borderWidth?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logoCloud?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    name?: T;
                    image?: T;
                    url?: T;
                    id?: T;
                  };
              appearance?:
                | T
                | {
                    contentWidth?: T;
                    background?: T;
                    rounded?: T;
                    paddingTop?: T;
                    paddingRight?: T;
                    paddingBottom?: T;
                    paddingLeft?: T;
                    marginTop?: T;
                    marginRight?: T;
                    marginBottom?: T;
                    marginLeft?: T;
                    borderTop?: T;
                    borderRight?: T;
                    borderBottom?: T;
                    borderLeft?: T;
                    borderWidth?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              body?: T;
              submitLabel?: T;
              successMessage?: T;
              appearance?:
                | T
                | {
                    contentWidth?: T;
                    background?: T;
                    rounded?: T;
                    paddingTop?: T;
                    paddingRight?: T;
                    paddingBottom?: T;
                    paddingLeft?: T;
                    marginTop?: T;
                    marginRight?: T;
                    marginBottom?: T;
                    marginLeft?: T;
                    borderTop?: T;
                    borderRight?: T;
                    borderBottom?: T;
                    borderLeft?: T;
                    borderWidth?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              appearance?:
                | T
                | {
                    contentWidth?: T;
                    background?: T;
                    rounded?: T;
                    paddingTop?: T;
                    paddingRight?: T;
                    paddingBottom?: T;
                    paddingLeft?: T;
                    marginTop?: T;
                    marginRight?: T;
                    marginBottom?: T;
                    marginLeft?: T;
                    borderTop?: T;
                    borderRight?: T;
                    borderBottom?: T;
                    borderLeft?: T;
                    borderWidth?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              appearance?:
                | T
                | {
                    contentWidth?: T;
                    background?: T;
                    rounded?: T;
                    paddingTop?: T;
                    paddingRight?: T;
                    paddingBottom?: T;
                    paddingLeft?: T;
                    marginTop?: T;
                    marginRight?: T;
                    marginBottom?: T;
                    marginLeft?: T;
                    borderTop?: T;
                    borderRight?: T;
                    borderBottom?: T;
                    borderLeft?: T;
                    borderWidth?: T;
                  };
              id?: T;
              blockName?: T;
            };
        latestPosts?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              limit?: T;
              appearance?:
                | T
                | {
                    contentWidth?: T;
                    background?: T;
                    rounded?: T;
                    paddingTop?: T;
                    paddingRight?: T;
                    paddingBottom?: T;
                    paddingLeft?: T;
                    marginTop?: T;
                    marginRight?: T;
                    marginBottom?: T;
                    marginLeft?: T;
                    borderTop?: T;
                    borderRight?: T;
                    borderBottom?: T;
                    borderLeft?: T;
                    borderWidth?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  customCSS?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  excerpt?: T;
  searchText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "headerNavigation".
 */
export interface HeaderNavigation {
  id: number;
  items?:
    | {
        label: string;
        /**
         * Optional Lucide icon displayed alongside the link label.
         */
        icon?:
          | (
              | 'book-open'
              | 'external-link'
              | 'github'
              | 'home'
              | 'info'
              | 'linkedin'
              | 'mail'
              | 'search'
              | 'shopping-bag'
              | 'user'
              | 'youtube'
              | 'twitter'
            )
          | null;
        /**
         * Hide the visible label. The link label remains available to screen readers.
         */
        iconOnly?: boolean | null;
        type: 'page' | 'post' | 'url';
        page?: (number | null) | Page;
        post?: (number | null) | Post;
        url?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Keep the header visible while the visitor scrolls.
   */
  sticky?: boolean | null;
  /**
   * Show the built-in Search link after the navigation items.
   */
  showSearch: boolean;
  /**
   * Optional icon that replaces the visible Search label.
   */
  searchIcon?:
    | (
        | 'book-open'
        | 'external-link'
        | 'github'
        | 'home'
        | 'info'
        | 'linkedin'
        | 'mail'
        | 'search'
        | 'shopping-bag'
        | 'user'
        | 'youtube'
        | 'twitter'
      )
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footerNavigation".
 */
export interface FooterNavigation {
  id: number;
  items?:
    | {
        label: string;
        type: 'page' | 'post' | 'url';
        page?: (number | null) | Page;
        post?: (number | null) | Post;
        url?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  siteTitle: string;
  appTitle: string;
  shortName: string;
  /**
   * Logo shown in light mode. The site title is used when this is empty.
   */
  lightLogo?: (number | null) | Media;
  /**
   * Logo shown in dark mode. The site title is used when this is empty.
   */
  darkLogo?: (number | null) | Media;
  /**
   * Website favicon and web-app manifest icon. Use a square PNG or SVG.
   */
  favicon?: (number | null) | Media;
  theme: {
    /**
     * Used when a visitor has not saved a light or dark preference.
     */
    defaultMode: 'system' | 'light' | 'dark';
    allowToggle: boolean;
    fontPreset: 'poppins' | 'system';
    shapePreset: 'square' | 'soft' | 'rounded';
    densityPreset: 'compact' | 'comfortable' | 'spacious';
    light: {
      primary: string;
      primaryInk: string;
      accent: string;
      surface: string;
      surfaceRaised: string;
      ink: string;
      inkMuted: string;
      border: string;
    };
    dark: {
      primary: string;
      primaryInk: string;
      accent: string;
      surface: string;
      surfaceRaised: string;
      ink: string;
      inkMuted: string;
      border: string;
    };
  };
  /**
   * Fallback description for pages without their own SEO description.
   */
  siteDescription: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "headerNavigation_select".
 */
export interface HeaderNavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        icon?: T;
        iconOnly?: T;
        type?: T;
        page?: T;
        post?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  sticky?: T;
  showSearch?: T;
  searchIcon?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footerNavigation_select".
 */
export interface FooterNavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        post?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  appTitle?: T;
  shortName?: T;
  lightLogo?: T;
  darkLogo?: T;
  favicon?: T;
  theme?:
    | T
    | {
        defaultMode?: T;
        allowToggle?: T;
        fontPreset?: T;
        shapePreset?: T;
        densityPreset?: T;
        light?:
          | T
          | {
              primary?: T;
              primaryInk?: T;
              accent?: T;
              surface?: T;
              surfaceRaised?: T;
              ink?: T;
              inkMuted?: T;
              border?: T;
            };
        dark?:
          | T
          | {
              primary?: T;
              primaryInk?: T;
              accent?: T;
              surface?: T;
              surfaceRaised?: T;
              ink?: T;
              inkMuted?: T;
              border?: T;
            };
      };
  siteDescription?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}